// Portfolio data — Gurinder Singh · 2026 YTD (Dec 2025 – Jul 11, 2026)
// Ghibli art + hackathon videos streamed from the live repo CDN.
const CDN = "https://raw.githubusercontent.com/Ripnrip/guriboycodes-portfolio/claude-portfolio/public";
const ghibli = (slug) => `${CDN}/images/projects/${slug}-ghibli.png`;
const vid = (file) => `assets/videos/${file}`;

window.PORTFOLIO_DATA = {
  cdn: CDN,
  hero: {
    name: "Gurinder Singh",
    handle: "guriboycodes",
    title: "Staff Software Engineer · Mobile & AI",
    location: "New York, NY",
    period: "2020 — Present",
    pitch: "Building the nervous system for agentic engineering.",
    typed: [
      "One connected learning loop — observe, understand, decide, execute, validate.",
      "I build the platforms other engineers ship on.",
      "I turn emerging AI into products used by 90M+.",
    ],
    pitchAlt: "A decade turning prototypes into products used by 90M+ — iOS platform architecture and applied-AI systems at PayPal / Venmo. Patent holder, Official Bar Raiser, two-time hackathon winner.",
    portrait: "assets/me-ghibli.png",
    portraitAlt: "assets/me-paragliding.jpeg",
    portraitExtra: "assets/events/compiling-mask.png",
  },

  stats: [
    { value: "90M+", label: "Users impacted" },
    { value: "500+", label: "Bar Raiser interviews" },
    { value: "3", label: "Business units" },
    { value: "28+", label: "Hackathons" },
    { value: "2×", label: "First-place wins" },
    { value: "1", label: "Patent holder" },
  ],

  flagship: [
    {
      id: "maia",
      cover: "ghibli-maia",
      image: "assets/covers/maia.jpg",
      codename: "MAIA × Venmo",
      title: "Cold-start to a unified PayPal program",
      tagline: "An AI agent that takes a new merchant from sign-up to live in about 20 minutes — work that used to take roughly three months.",
      status: "Pilots in flight",
      stamp: "P0 validated · cohort pilots",
      window: "Apr 10 → Jul 2026",
      sponsor: "Migration & Upgrade Program lead · MAIA PM · my manager",
      story: "I built an autonomous agent that walks a merchant through onboarding end to end. Over one weekend I grew the test set from 332 to 9,513 real businesses so the team finally had real-world ground truth, then demoed it live to 14 senior leaders: two real storefronts upgraded and accepting Venmo in about 20 minutes, on stage.",
      stack: ["LLM Agents", "RAG", "D3.js", "CommonCrawl", "AWS Athena", "Remotion"],
      metrics: [
        { k: "Onboarding", v: "~3 mo → 20 min" },
        { k: "Businesses scored", v: "9,513" },
        { k: "Pilot cohort", v: "Live merchants" },
        { k: "Status", v: "In production" },
      ],
      accent: "cyan",
    },
    {
      id: "darwin",
      cover: "ghibli-darwin",
      image: "assets/covers/darwin.jpg",
      codename: "Darwin",
      title: "Evolution framework, now productionized",
      tagline: "A system that improves AI skills on its own — and records every attempt, so it learns from its own history.",
      status: "Production + Council pilot",
      stamp: "Council live · Analytics Home",
      window: "2026 · productionized Jun 30",
      sponsor: "AI Toolkit lead · AI Labs",
      story: "If a task has a prompt going in, an answer coming out, and a way to score that answer, Darwin can improve it automatically: try many variations, keep the best, and open a pull request with the upgrade. Every attempt is saved with its score and the reasoning behind it, so each round builds on the last. It plugs into any code repository with no setup.",
      stack: ["GEPA", "DSPy", "Cosmos", "Graph DB", "GitHub Actions"],
      metrics: [
        { k: "What it does", v: "Self-improves AI skills" },
        { k: "Candidate pool", v: "1,020 variations" },
        { k: "Integrates with", v: "Any repo, zero setup" },
        { k: "Output", v: "Scored PR with full diff" },
      ],
      vocabulary: ["Seed", "Zephyr", "Polaris", "Compass", "Bloom", "Fossil", "Garden", "Gardener"],
      accent: "amber",
    },
    {
      id: "vireo",
      cover: "ghibli-vireo",
      image: "assets/covers/vireo.jpg",
      codename: "Vireo",
      title: "Telemetry + memory for AI dev workflows",
      tagline: "A flight recorder for AI agents — it captures everything they do, then remembers it.",
      status: "Production · v3",
      stamp: "Devmo §7 + §8 owner",
      window: "2026 ongoing",
      sponsor: "Devmo platform team · Venmo AI Council",
      story: "AI agents are hard to trust because you can't see what they actually did. Vireo records their actions from four different entry points and distills the logs into a memory the next run can draw on. It installs in two minutes and became the team's standard for watching agents in production.",
      stack: ["MCP", "n8n", "OpenTelemetry", "OpenInference", "Python", "Swift"],
      metrics: [
        { k: "What it is", v: "AI flight recorder" },
        { k: "Captures from", v: "4 entry points" },
        { k: "Adopted as", v: "team standard" },
        { k: "Install", v: "2 minutes" },
      ],
      accent: "emerald",
    },
    {
      id: "cosmos",
      cover: "ghibli-cosmos",
      image: "assets/covers/cosmos.jpg",
      codename: "claude-cosmos",
      title: "The universal LLM capture layer",
      tagline: "One safe doorway every AI request passes through — scrubbing sensitive data before it ever leaves.",
      status: "Live in prod",
      stamp: "The surface Vireo can't reach",
      window: "Q1–Q2 2026",
      sponsor: "Devmo · AI Toolkit lead",
      story: "When dozens of internal tools all talk to AI models, that traffic needs a single safe doorway. claude-cosmos is it: every request routes through one place, gets stripped of personal data, and is logged for safety. It covers the hosted and third-party tools that a local recorder like Vireo can't see.",
      stack: ["Anthropic API", "MCP", "PII Scrubbing", "Cosmos"],
      metrics: [
        { k: "What it is", v: "Safe AI gateway" },
        { k: "Protects", v: "PII before it leaves" },
        { k: "In production", v: "6+ tools" },
      ],
      accent: "violet",
    },
    {
      id: "miam",
      cover: "ghibli-mac",
      image: "assets/covers/nested-silicon.jpg",
      codename: "Nested macOS Runtime",
      title: "PayPal's first macOS-in-macOS substrate",
      tagline: "Running a Mac inside a Mac to make the iOS test suite 3× faster — on the same hardware.",
      status: "Handoff active",
      stamp: "CI + agent substrate · 3.0× proven",
      window: "Foundation · Q1 2026",
      sponsor: "iOS leadership · senior eng director · Livery lead",
      story: "iOS test runs were painfully slow. I was the first at the company to run a macOS virtual machine inside a macOS host, which let the test suite run in parallel. The first result: a run that took 22m 38s finished in 7m 23s — three times faster, on the same laptops, with no changes to the tests themselves.",
      stack: ["Virtualization.framework", "tart", "lume", "macOS", "Swift"],
      metrics: [
        { k: "iOS test suite", v: "22:38 → 7:23" },
        { k: "Speed", v: "3× faster" },
        { k: "New hardware", v: "none" },
      ],
      accent: "rose",
    },
    {
      id: "devmo",
      cover: "ghibli-devmo",
      image: "assets/covers/devmo.jpg",
      codename: "Devmo",
      title: "Platform integration & prompt enhancer",
      tagline: "The execution layer where Vireo telemetry and Darwin intelligence meet real developer workflows.",
      status: "GA · pilot readiness",
      stamp: "k8s telemetry in flight",
      window: "2026 ongoing",
      sponsor: "Devmo platform team",
      story: "Devmo is where the agentic infrastructure becomes tangible for engineers. I brought Vireo telemetry into both in-process and Kubernetes agent runtimes, added skill-read and session-end signals to distinguish helpful skills from merely present ones, and built session classification that catches failures invisible at the individual tool-call level. The Prompt Enhancer and Guardrails — including a ~90-test prompt-injection battery — are now in the canonical repo.",
      stack: ["Vireo", "OpenTelemetry", "Python", "Kubernetes", "GitHub Actions"],
      metrics: [
        { k: "Prompt safety", v: "Injection-resistant" },
        { k: "Observability", v: "Cloud + local agents" },
        { k: "Status", v: "Generally available" },
      ],
      accent: "cyan",
    },
  ],



  // Pre-built RAG knowledge base for "Ask My Brain"
  brain: {
    nodes: [
      { id: "maia", label: "MAIA × Venmo", kind: "system", x: 0.5, y: 0.3 },
      { id: "vireo", label: "Vireo", kind: "system", x: 0.25, y: 0.5 },
      { id: "cosmos", label: "claude-cosmos", kind: "system", x: 0.75, y: 0.5 },
      { id: "darwin", label: "Darwin", kind: "system", x: 0.3, y: 0.75 },
      { id: "miam", label: "Nested macOS Runtime", kind: "system", x: 0.7, y: 0.75 },

      { id: "merchants", label: "9,513 merchants", kind: "metric", x: 0.55, y: 0.15 },
      { id: "devmo", label: "Devmo", kind: "system", x: 0.5, y: 0.55 },
      { id: "agent0", label: "Agent-0", kind: "system", x: 0.85, y: 0.7 },
      { id: "livery", label: "Livery", kind: "program", x: 0.85, y: 0.85 },
      { id: "fossils", label: "1,020 Fossils", kind: "metric", x: 0.15, y: 0.85 },
      { id: "gepa", label: "GEPA + DSPy", kind: "tech", x: 0.1, y: 0.65 },
      { id: "mcp", label: "MCP", kind: "tech", x: 0.15, y: 0.35 },
      { id: "otel", label: "OTel export", kind: "tech", x: 0.4, y: 0.4 },
      { id: "video", label: "video-toolkit", kind: "tech", x: 0.62, y: 0.68 },
      { id: "venmo", label: "Venmo (90M users)", kind: "program", x: 0.5, y: 0.92 },
    ],
    edges: [
      ["maia", "vireo"], ["maia", "cosmos"], ["maia", "merchants"],
      ["vireo", "devmo"], ["vireo", "mcp"], ["vireo", "cosmos"], ["vireo", "otel"],
      ["cosmos", "agent0"], ["cosmos", "devmo"],
      ["darwin", "gepa"], ["darwin", "fossils"], ["darwin", "cosmos"], ["darwin", "video"],
      ["miam", "agent0"], ["miam", "livery"],
      ["agent0", "livery"], ["maia", "venmo"], ["maia", "video"], ["otel", "livery"],

      ["devmo", "vireo"], ["devmo", "maia"],
    ],

    corpus: [
      { id: "k1", topic: "MAIA", text: "MAIA × Venmo went from a 4-step AIM pipeline (aim_init_check → aim_convert_router → aim_correction → aim_paypal_ft) to a 20-minute live executive demo on April 29, 2026 in Austin. Took 84–89 days of Venmo onboarding to 20 minutes on stage, upgrading two real merchant sites V5 → V6 and enabling Venmo." },
      { id: "k2", topic: "MAIA", text: "Over one weekend (Apr 14) I scaled the test corpus from 332 → 9,513 scored US merchants across 18 independent harvest campaigns (CommonCrawl + AWS Athena + specialty hunters like enterprise_hunter, legacy_hunter, mega_r2). Identified 476 prime Venmo V1 candidates in the bullseye. Singapore's MAIA team had zero real-world telemetry; I gave them ground truth." },
      { id: "k3", topic: "MAIA", text: "On May 4, 2026 the program lead unified the program: Venmo upgrade should not be a separate track. By June 26 the standalone Venmo working group folded into the single PayPal Migration & Upgrade Program. On June 8 the MAIA PM named me to the MAIA build core. Now moving from demo to first contained live cohort pilots." },
      { id: "k4", topic: "Darwin", text: "Darwin is an evolution framework: anything with a prompt in, an output out, and a judge that can score it is GEPA-evolvable. Loop: Evolve → Evaluate → Preserve → Explain → Open PR. Regressions are not failure; they are scientific signal. Vocabulary: Seed, Zephyr, Polaris, Compass, Bloom, Fossil, Garden, Gardener." },
      { id: "k5", topic: "Darwin", text: "Darwin productionized in mid-2026: invokable from any repo three ways with no fork (reusable workflow, composite action, repository_dispatch). PR-gate auto-runs on any skill change and posts a score-delta sticky comment. First clean end-to-end Bloom PR landed (#45 → #46). ~120 evolution runs against the real Pay-with-Venmo skill registry. Now lives in the PayPal-Venmo org with CI (DPEIR-4171)." },
      { id: "k6", topic: "Darwin", text: "Output: 71 PRs across two milestones (37 + 34). Every PR ships a narrated video, score table, candidate arena, judge prompt, eval dataset, and full diff. The fossil record is a graph DB with full-text search: 1,020 candidates, 19 judges, 678 eval examples, cross-milestone lineage. Doctrinally aligned with NousResearch's hermes-agent-self-evolution and Imbue's Darwinian Evolver." },
      { id: "k7", topic: "Vireo", text: "Vireo is agent-agnostic event capture across four surfaces (MCP server, CLI vireo-send, shell hooks, skill instructions) feeding a 33-field schema into an n8n pipeline. Distills hourly into five memory kinds: procedural, failure, preference, semantic, episodic. 2-minute install via ./start.sh. Owns Devmo Workstreams §7 (Telemetry) + §8 (Memory)." },
      { id: "k8", topic: "Vireo", text: "Vireo v2 shipped RAG, per-sub-agent telemetry, and a unified OpenInference + OpenTelemetry export (Devmo PRs #128/#165) so Livery, Datadog, and Langtrace can consume the stream. Memory-stack v2 is a cross-language Python + Swift hybrid. Captured a full MAIA run end-to-end on May 15: 53 events, 45 traces, 40 tool calls, 10 skill events, 100% success in ~8 min." },
      { id: "k9", topic: "claude-cosmos", text: "claude-cosmos is a Claude-flavored proxy routing any Anthropic-shape request to PayPal's Cosmos LLM endpoints, with PII scrubbing, sanitization, and telemetry built into the proxy itself. It's the capture surface Vireo's hooks can't reach: hosted, ephemeral, and third-party agents. Used by Osaurus, NousResearch Hermes Agent, Agent-0, Cosmos-IDE, and the Devmo webapp." },
      { id: "k10", topic: "claude-cosmos", text: "The frame: Vireo catches what an agent intends to do on local CLI/IDE; claude-cosmos catches what every agent actually says to the model over the wire. Every call has to come through it to reach Cosmos at all, so capture is automatic and uniform — sanitization and PII scrub live in one place. It's now MAIA's network-layer telemetry path (DTVZ-506)." },
      { id: "k11", topic: "Nested macOS Runtime", text: "The Nested macOS Runtime (formerly Mac-in-a-Mac): PayPal's first macOS guest VM running inside a macOS host (Apple's Virtualization.framework + cirruslabs/tart). First measured result: PayWithVenmo plan 22m 38s → 7m 23s (3.0× speedup) on existing hardware — no cloud, no new minis, no test modifications. Now the runtime substrate Livery and Agent-0 both run on. iOS sponsor signed May 5: 'I am sold on the performance.'" },
      { id: "k12", topic: "Nested macOS Runtime", text: "The nested VM also provided the sanctioned, isolated containment that let me run external-agent (Hermes) research safely, as CDC/InfoSec confirmed in June. Every iOS team can shard test plans across host + 1–2 child VMs per Mac mini: 120-test suites become 3 shards of 40 running in parallel. Operational ownership is handing off to the iOS team and a peer engineer via lume." },
      { id: "k13", topic: "Mid-year", text: "Since the May checkpoint: Darwin productionized with a live Council pilot, Vireo v3 reconciliation, Cerebro organizational memory, the MAIA track folded into one program moving to live pilots, a new shared video-toolkit repo (Remotion 4.0 + Google Veo / Chirp3-TTS, runs from GitHub Actions), and a Hermes security-review exchange that elevated the agent-evolution work to the enterprise AI-tools evaluation." },
      { id: "k14", topic: "Mid-year", text: "Devmo Prompt Enhancer + Guardrails migrated into the canonical Devmo repo (PRs #59 Guard Rails, #60 Prompt Enhancer); guardrails ship with ~90 tests including a prompt-injection battery. Also raised a skill supply-chain safety policy ('no URLs in skills') after ~820 malicious skills were found in a public hub." },
      { id: "k15", topic: "Scope", text: "Scope expansion: started December 2025 as iOS Sandbox DRI on Pay With Venmo (TestFlight pipeline, Ladybug debug menu, daily E2E call ownership). By July 2026: owner of the Vireo telemetry + memory layer, originator of the Nested macOS Runtime, architect of Darwin and Cerebro, and named to the MAIA build core. The work crosses 3 BUs (Venmo, SMB-FS, LE/GSA), sponsored at Senior Director / VP-adjacent level." },
      { id: "k16", topic: "Venmo", text: "Earlier iOS impact at Venmo: QRC Widget Patent (2022) — first team to use SwiftUI for iOS widgets at Venmo, reduced user friction by 66%. Dynamic Island / Live Activities / App Clip infrastructure. Pay With Venmo Checkout cut pay-sheet render latency by ~2 seconds. Gift Cards for Amazon and Starbucks. QRC moonshot led to a $60M CVS contract; Amex partnership for a $400M deal." },
      { id: "k17", topic: "Hackathons", text: "28+ hackathons across 6+ countries. Two first-place wins: MLH @ Bloomberg London 2017 (Automated Search & Rescue System, featured in a BBC documentary) and Devcamp NYC 2016 (Talent Management App, won among 300+ at Google NYC). HackZurich 2018 finalist (AR Car Buying Tool, top of 400+). Judge twice at Hack Yale." },
      { id: "k18", topic: "Philosophy", text: "Human-centered applied AI: elevate human skill, judgment, and ethos through careful system design. The 'Stay to the plan' hook is a 20-line markdown file that solves the same problem people throw 20K-token prompts at — a deterministic ring around multi-sub-agent autonomy. Most of the logic lives in markdown, not code: a glimpse of what the future of coding looks like." },
      { id: "k19", topic: "Philosophy", text: "Three principles: (1) Platform over features — build the substrate (telemetry, proxies, evolution frameworks) that lets others ship. (2) Observability as architecture — Vireo catches intent locally, claude-cosmos catches every call over the wire; together that's total coverage. (3) Ship then evolve — regressions are scientific signal, not failure, proven by Darwin's 1,020-candidate fossil record." },
      { id: "k20", topic: "Hackathons", text: "Hackathon film reel: MLH Prime 2017 in London (Bloomberg) won 1st place with a DJI-drone Search & Rescue system using IBM Watson facial recognition, featured in a BBC documentary. HackZurich 2022 won 1st place with 'Elate' (sponsored by Schindler). HackZurich 2021 was a solo build, ARon — an AR fitness coach using CreateML + ARKit pose detection with Garmin integration. There are videos of all three." },
      { id: "k21", topic: "Leadership", text: "Official Bar Raiser at PayPal/Venmo: 500+ technical interviews across iOS, system design, and AI/ML; final decision-maker on critical hiring rounds; mentored 20+ engineers to promotion. Interfaith ERG Chapter Lead for the Sikh community (founded, grew to 150+ members globally). Judge twice at Hack Yale, mentor at PennApps, advisory board at Bayside High School's CTE program." },
      { id: "k22", topic: "Side projects", text: "Beyond PayPal: Flow (Dynamic Island iOS app), Ethereal Dimension (AI storytelling platform with Three.js worlds), Zai Vision Suite (GLM-4.6V computer vision), a RAG Rosicrucian Knowledge Explorer, Agentic News Transformer (LangChain + CrewAI), published App Store apps (Hylios game, Rosicrucian Vowel Sounds), and open-source dev tools (TweakCC for Claude Code, CodeFlow architecture maps, Scarf — a native Hermes agent GUI)." },
      { id: "k23", topic: "Scope", text: "Working style: I gravitate to the load-bearing substrate nobody else owns yet, get named senior sponsorship fast, and hand off cleanly once it's productionized (Nested macOS Runtime to the iOS team, Darwin to AI Labs). I narrate everything — D3 knowledge graphs, Remotion explainer videos, score-delta PR comments — so the work is legible to leaders, not just other engineers." },

      { id: "k26", topic: "July 2026", text: "The July 2026 story: Darwin gained governed multi-model Council review (dual-model pilot proven on PR #86, Jul 11), Analytics Home, bounded Foresight (read-only Jira), and Distillery lesson gates with cryptographic approval binding. Vireo shipped v3 reconciliation (Vireo #9) and wired end-to-end into Devmo agent runtimes (#309 merged; #335/#336 emitting spans from k8s and in-process agents). The Nested macOS Runtime handoff went active, with Livery and Agent-0 both running on it as their substrate." },
      { id: "k27", topic: "The loop", text: "Five systems form one connected learning loop: (1) OBSERVE — Vireo captures structural agent and product signals across Claude Code, Codex, Cursor, Gemini, MCP clients, shell CLIs, and historical session backfills. (2) DECIDE — Darwin runs the inner loop (GEPA prompt evolution, 1,020 candidates, 71 PRs) and the outer loop (Council review, lesson gates, cryptographic approval binding) — the decision engine that makes the whole system self-improving. (3) EXECUTE — MAIA is the agentic solution at scale; it applies Darwin-refined intelligence to real merchant workflows and gets measurably better with every Vireo-observed cycle. (4) SUBSTRATE — the Nested macOS Runtime provides safe, fully-agentic e2e runs with 3× parallelized build times — the isolated environment where the loop can run without risk. (5) PLATFORM — Devmo is where the telemetry and intelligence meet real developer workflows, closing the loop back to Vireo. 408 PRs, 7 major programs, VP-adjacent sponsorship across 3 BUs." },
      { id: "k28", topic: "Roadmap", text: "Roadmap from the audit — Now (July): validate Devmo telemetry and skill signals in QA, finish Darwin battle proofs and storage onboarding, land Vireo reconciliation and emitter packages, run the MAIA test bed. Next (Aug–Sep): retrieve one observed lesson and improve a later task, expose productivity/reliability/learning analytics, validate Foresight against a bounded real sprint. Later (Q4): govern the learning flywheel across agents and products, scale merchant experiments, publish high-confidence lessons as versioned capabilities." },
      { id: "k24", topic: "Hire", text: "Why hire Gurinder: in seven months he built five productionized, cross-BU AI-platform systems with VP-adjacent sponsorship, took 84–89-day merchant onboarding to a 20-minute executive demo, delivered a 3.0× iOS test speedup, and authored 408 PRs — while also being an Official Bar Raiser (500+ interviews) and a patent holder. He builds platforms others ship on, communicates impact to leadership, and turns ambiguous greenfield into named, sponsored, handed-off infrastructure." },
      { id: "k29", topic: "Devmo", text: "Devmo is the execution layer where Vireo telemetry and Darwin intelligence meet real developer workflows. I brought Vireo telemetry into both in-process and Kubernetes agent runtimes, added skill-read and session-end signals to distinguish helpful skills from merely present ones, and built session classification that catches failures invisible at the individual tool-call level. Prompt Enhancer and Guardrails (~90 tests including a prompt-injection battery) are now in the canonical repo. Devmo #309 merged Jul 8; PRs #335/#336 emit Vireo spans from k8s and in-process runtimes." },
      { id: "k30", topic: "Nested macOS Runtime", text: "The Nested macOS Runtime is the safe substrate for fully-agentic end-to-end runs. I built PayPal's first macOS-in-macOS VM (Apple Virtualization.framework + tart/lume), proving a 3.0× iOS test speedup (22m 38s → 7m 23s) on existing hardware by parallelizing test shards across host + child VMs. It became the runtime substrate Livery and Agent-0 both run on, and the VM-isolated containment that let Hermes research run safely (CDC/InfoSec confirmed June). Handoff to the iOS team is now active." },

      { id: "k32", topic: "AI Enablement", text: "AI Enablement is the broader platform work: stabilized internal model access across containerized and macOS virtualized environments, built knowledge-graph and skill-graph experiences that make internal capabilities discoverable, and created reusable video, audio, PR-demo, and evidence workflows for technical communication. DX Sounds MCP server (8 themes, 14 tools) merged into PayPal AI Hub May 4." },
    ],

    examples: [
      "What's MAIA and why does it matter?",
      "How did Darwin get productionized?",
      "What's new in Vireo v3?",
      "How do Vireo and Darwin make MAIA smarter over time?",
      "How do all five systems connect?",
      "What is the connected learning loop?",
      "Why should we hire him?",
    ],
  },

  experience: [
    {
      company: "PayPal / Venmo",
      role: "Staff iOS Engineer → Staff Software Engineer · Mobile & AI",
      window: "2019 — Present",
      logo: "assets/logos/paypal.svg",
      logoAlt: "assets/logos/venmo.png",
      bullets: [
        "Authored five production AI-platform systems — Vireo, Darwin, MAIA, Nested macOS Runtime, and Devmo — turning AI prototypes into canonical platform programs adopted across the org.",
        "Built one connected learning loop: Vireo observes agent work, Darwin runs the inner and outer evolution loop, MAIA executes the intelligence at scale and gets better with every cycle, and the Nested macOS Runtime provides the safe fully-agentic substrate that makes it all possible.",
        "QRC Widget patent holder — first SwiftUI iOS widget at Venmo, cutting user friction 66%; shipped Venmo Gift Cards (Amazon, Starbucks) and Pay With Venmo for JetBlue.",
        "Official Bar Raiser — 500+ technical interviews over his career; leads interviews and cross-team AI enablement, mentoring engineers into responsible agentic workflows.",
      ],
    },
    {
      company: "Google Stadia",
      role: "iOS Developer / Consultant",
      window: "2018 — 2019",
      logo: "assets/logos/stadia.png",
      bullets: [
        "Supported launch readiness for Stadia cloud gaming on mobile — Flutter/Dart with native iOS plugins.",
        "Implemented low-latency Core Bluetooth controller connectivity.",
        "Profiled CPU/GPU with Xcode Instruments to improve launch-quality stability.",
      ],
    },
    {
      company: "Morgan Stanley",
      role: "iOS Engineer",
      window: "2016 — 2018",
      logo: "assets/logos/morgan-stanley.png",
      bullets: [
        "Modernized Wealth Management mobile experiences for ultra-high-net-worth clients.",
        "Built check-deposit, biometric auth, certificate-pinning, and jailbreak detection.",
        "Migrated core iOS code from Objective-C toward Swift atop hybrid Cordova infrastructure.",
      ],
    },
  ],

  hackathonStats: [
    { value: "28+", label: "Hackathons" },
    { value: "6+", label: "Countries" },
    { value: "2", label: "First-place wins" },
    { value: "2×", label: "Judged at Yale" },
  ],

  // lat/lng markers for the globe — cities on the hackathon circuit
  hackathonMarkers: [
    { location: [51.5074, -0.1278], size: 0.10, label: "London 🇬🇧" },
    { location: [40.7128, -74.006], size: 0.11, label: "New York 🇺🇸" },
    { location: [47.3769, 8.5417], size: 0.10, label: "Zurich 🇨🇭" },
    { location: [41.3874, 2.1686], size: 0.07, label: "Barcelona 🇪🇸" },
    { location: [55.6761, 12.5683], size: 0.06, label: "Copenhagen 🇩🇰" },
    { location: [37.7749, -122.4194], size: 0.07, label: "San Francisco 🇺🇸" },
    { location: [35.6762, 139.6503], size: 0.07, label: "Tokyo 🇯🇵" },
  ],

  hackathons: [
    { place: "1st", year: "2016", name: "Devcamp NYC — Google NYC", flag: "🇺🇸", img: "assets/events/devcamp-nyc.jpg", desc: "Talent Management App — first place among 300+ participants at Google NYC.", win: true },
    { place: "Team", year: "2023", name: "HackZurich — Legal Lunatics", flag: "🇨🇭", img: "assets/events/legal-lunatics.jpg", desc: "Implenia-sponsored build with a returning 5-person crew." },
    { place: "Judge", year: "2022", name: "Hack Yale (2×)", flag: "🇺🇸", img: "assets/events/hack-yale.jpg", desc: "Evaluated technical feasibility & innovation for 500+ participants." },
    { place: "Mentor", year: "—", name: "PennApps — UPenn", flag: "🇺🇸", img: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663074533385/ouubxQbTilpimrkl.png", desc: "Mentored students through complex mobile & AI implementations." },
    { place: "Conf", year: "—", name: "try! Swift Tokyo", flag: "🇯🇵", img: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663074533385/qhNzKRZaxTNrIjsn.png", desc: "iOS community conference in Tokyo — plugged into the global Swift network." },
    { place: "Conf", year: "2018", name: "dotSwift — Paris", flag: "🇫🇷", img: "assets/events/dotswift-paris.jpg", desc: "iOS conference in Paris — with Paul Hudson (@twostraws) of Hacking with Swift." },
    { place: "Giving back", year: "2019", name: "Bayside High School", flag: "🇺🇸", imgs: ["assets/events/bayside-high-school-mentor.jpg", "assets/events/bayside-high-school-stage.jpg"], desc: "Mentored students at Queens College — hands-on coding workshops and a keynote on breaking into tech." },
  ],

  // Full skill catalog — group / color / icon / proficiency.
  // Feeds both the Skills section AND the Ask-My-Brain knowledge graph (icon nodes).
  skills: [
    {
      group: "AI / ML & Agents",
      key: "ai",
      accent: "violet",
      items: [
        { name: "Python", icon: "assets/tech/python.svg", level: 96 },
        { name: "Claude", icon: "assets/tech/claude.svg", level: 96 },
        { name: "OpenAI", icon: "assets/tech/openai.svg", level: 94 },
        { name: "Gemini", icon: "assets/tech/gemini.png", level: 92 },
        { name: "Ollama", icon: "assets/tech/ollama.svg", level: 88 },
        { name: "LangChain", icon: "assets/tech/langchain.svg", level: 93 },
        { name: "LangGraph", icon: "assets/tech/langgraph.svg", level: 88 },
        { name: "LlamaIndex", icon: "assets/tech/llamaindex.png", level: 86 },
        { name: "CrewAI", icon: "assets/tech/crewai.svg", level: 85 },
        { name: "MCP", icon: "assets/tech/mcp.svg", level: 95 },
        { name: "DSPy / GEPA", icon: "assets/tech/python.svg", level: 90 },
        { name: "RAG Pipelines", icon: "assets/tech/rag-pipelines.svg", level: 95 },
        { name: "PyTorch", icon: "assets/tech/pytorch.svg", level: 84 },
        { name: "MLX", icon: "assets/tech/mlx.svg", level: 86 },
        { name: "Stable Diffusion", icon: "assets/tech/stable-diffusion.svg", level: 82 },
        { name: "OpenCV", icon: "assets/tech/opencv.svg", level: 80 },
        { name: "Hugging Face", icon: "assets/tech/hugging-face.svg", level: 84 },
        { name: "Replicate", icon: "assets/tech/replicate.svg", level: 85 },
        { name: "TensorFlow", icon: "assets/tech/tensorflow.svg", level: 80 },
        { name: "OpenRouter", icon: "assets/tech/openrouter.svg", level: 85 },
        { name: "ElevenLabs", icon: "assets/tech/elevenlabs.svg", level: 86 },
      ],
    },
    {
      group: "Mobile / iOS",
      key: "mobile",
      accent: "cyan",
      items: [
        { name: "Swift", icon: "assets/tech/swift.svg", level: 96 },
        { name: "SwiftUI", icon: "assets/tech/swiftui.svg", level: 95 },
        { name: "Objective-C", icon: "assets/tech/objective-c.svg", level: 88 },
        { name: "ARKit", icon: "assets/tech/arkit.svg", level: 85 },
        { name: "RoomPlan", icon: "assets/tech/roomplan.png", level: 80 },
        { name: "CoreML", icon: "assets/tech/coreml.svg", level: 88 },
        { name: "ActivityKit", icon: "assets/tech/activitykit.svg", level: 95 },
        { name: "WidgetKit", icon: "assets/tech/widgetkit.png", level: 95 },
        { name: "MapKit", icon: "assets/tech/mapkit.svg", level: 88 },
        { name: "BLE / NFC", icon: "assets/tech/ble.svg", level: 88 },
        { name: "Xcode", icon: "assets/tech/xcode.svg", level: 94 },
        { name: "Flutter", icon: "assets/tech/flutter.svg", level: 82 },
        { name: "Dart", icon: "assets/tech/dart.svg", level: 80 },
        { name: "React Native", icon: "assets/tech/react-native.svg", level: 82 },
      ],
    },
    {
      group: "Cloud & DevOps",
      key: "cloud",
      accent: "emerald",
      items: [
        { name: "AWS", icon: "assets/tech/aws.svg", level: 90 },
        { name: "GCP", icon: "assets/tech/googlecloud.svg", level: 88 },
        { name: "Azure", icon: "assets/tech/azure.svg", level: 82 },
        { name: "Docker", icon: "assets/tech/docker.svg", level: 90 },
        { name: "GitHub Actions", icon: "assets/tech/github-actions.svg", level: 94 },
        { name: "Jenkins", icon: "assets/tech/jenkins.svg", level: 80 },
        { name: "Fastlane", icon: "assets/tech/fastlane.svg", level: 92 },
        { name: "Vercel", icon: "assets/tech/vercel.svg", level: 92 },
        { name: "Datadog", icon: "assets/tech/datadog.svg", level: 85 },
        { name: "Firebase", icon: "assets/tech/firebase.svg", level: 85 },
        { name: "RunPod", icon: "assets/tech/runpod.svg", level: 82 },
        { name: "n8n", icon: "assets/tech/n8n.svg", level: 90 },
      ],
    },
    {
      group: "Data & Tools",
      key: "data",
      accent: "amber",
      items: [
        { name: "PostgreSQL", icon: "assets/tech/postgresql.svg", level: 90 },
        { name: "MongoDB", icon: "assets/tech/mongodb.svg", level: 88 },
        { name: "Redis", icon: "assets/tech/redis.svg", level: 86 },
        { name: "Pinecone", icon: "assets/tech/pinecone.png", level: 92 },
        { name: "ChromaDB", icon: "assets/tech/chromadb.svg", level: 92 },
        { name: "Qdrant", icon: "assets/tech/qdrant.svg", level: 88 },
        { name: "Neo4j", icon: "assets/tech/neo4j.svg", level: 88 },
        { name: "GraphQL", icon: "assets/tech/graphql.svg", level: 84 },
        { name: "Next.js", icon: "assets/tech/nextjs.svg", level: 92 },
        { name: "React", icon: "assets/tech/react.svg", level: 92 },
        { name: "TypeScript", icon: "assets/tech/typescript.svg", level: 90 },
        { name: "NumPy", icon: "assets/tech/numpy.svg", level: 85 },
        { name: "Pandas", icon: "assets/tech/pandas.svg", level: 85 },
        { name: "Figma", icon: "assets/tech/figma.svg", level: 88 },
        { name: "GitHub", icon: "assets/tech/github.svg", level: 95 },
        { name: "Cursor", icon: "assets/tech/cursor.svg", level: 96 },
      ],
    },
  ],

  // Engineering philosophy — what it's like to build with me
  philosophy: {
    quote: "One connected learning loop: observe, understand, decide, execute, validate.",
    principles: [
      { title: "Platform over features", body: "The most durable engineering is substrate — telemetry layers, proxy surfaces, evolution frameworks. I build the platforms that let others ship, not just point features. Five systems, one loop." },
      { title: "Observability as architecture", body: "Vireo + claude-cosmos = total coverage. Intent captured locally, ground truth captured over the wire. Anywhere an LLM call can hide is a gap I close by design." },
      { title: "Ship, then evolve", body: "Darwin's fossil record proves it: regressions aren't failure, they're scientific signal. Every candidate that doesn't make it narrows the search space for the one that does." },
    ],
  },

  // "What it's like to work with me" — the easter-egg video + hackathon film reel
  media: {
    workWithMe: {
      title: "What it's like to work with me",
      blurb: "A behind-the-scenes look — equal parts demo energy and dad jokes. Click the 👀 in the corner, or here.",
      file: vid("working-with-me.mp4"),
    },
    reel: [
      { title: "Drone Search & Rescue", event: "MLH Prime 2017 · Bloomberg London", place: "1st place", note: "Featured in a BBC documentary. DJI drones + IBM Watson facial recognition to locate stranded people.", file: vid("mlh-2017-drone-bbc.mp4"), stills: ["assets/events/mlh-london-1st-prize.png"], flag: "🇬🇧" },
      { title: "Carly — AR Car Visualizer", event: "HackZurich 2018", place: "Finalist", note: "Voice-controlled AR car configurator — real-time 3D rendering, top of 400+ teams.", file: vid("hackzurich-carly.mp4"), stills: ["assets/events/hackzurich-2018-swissre.png"], flag: "🇨🇭" },
      { title: "ARon — AI Fitness Coach", event: "HackZurich 2021", place: "Solo build", note: "CreateML + ARKit real-time pose detection, Garmin biometric integration.", file: vid("hackzurich-2021-aron.mp4"), flag: "🇨🇭" },
      { title: "Elate — Schindler Group", event: "HackZurich 2022", place: "1st place", note: "Winning hack built with a 5-person team on the Schindler-sponsored track.", file: vid("hackzurich-ar.mp4"), flag: "🇨🇭" },
    ],
  },

  // Side projects — real Ghibli-generated art, filterable
  sideProjects: [
    { title: "Flow", cat: "Mobile", feature: true, img: ghibli("flow"), one: "Dynamic Island, done beautifully.", desc: "Dynamic Island iOS app with rich state-driven animations and deep system integration.", tech: ["Swift", "SwiftUI", "Dynamic Island"], github: "https://github.com/Ripnrip/Flow" },
    { title: "Ethereal Dimension", cat: "Creative", feature: true, img: ghibli("ethereal-dimension"), one: "An AI-built storytelling universe.", desc: "AI storytelling platform — interactive narratives in immersive 3D worlds.", tech: ["React", "Three.js", "WebGL", "AI"], link: "https://ethereal-dimension-nextjs.vercel.app", github: "https://github.com/Ripnrip/EtherealDimension" },
    { title: "Zai Vision Suite", cat: "AI/ML", feature: true, img: ghibli("zai-vision-suite"), one: "AI that understands what it sees.", desc: "Multi-platform AI vision suite on GLM-4.6V — real-time analysis, detection, scene understanding.", tech: ["Python", "GLM-4.6V", "Computer Vision"], github: "https://github.com/Ripnrip/zai-vision-suite" },
    { title: "Rosicrucian Knowledge Explorer", cat: "AI/ML", img: ghibli("rosicrucian-knowledge-explorer"), one: "Ask centuries-old texts anything.", desc: "RAG-powered semantic search over esoteric texts with citation tracking.", tech: ["Python", "RAG", "Pinecone", "OpenAI"], link: "https://rosicrucian-knowledge-explorer.vercel.app" },
    { title: "Agentic News Transformer", cat: "AI/ML", img: ghibli("agentic-news-transformer"), one: "AI agents that curate the news.", desc: "Autonomous multi-agent ecosystem for curating and transforming news content.", tech: ["Python", "LangChain", "CrewAI"], github: "https://github.com/Ripnrip/Agentic-News-Transformer" },
    { title: "AI IDE Setup & Workflows", cat: "Tools", img: ghibli("ai-ide-setup"), one: "My AI pair-programming setup.", desc: "Dotfiles, scripts, and MCP server configs to maximize AI pair-programming.", tech: ["Bash", "MCP", "Cursor", "Claude"], github: "https://github.com/Ripnrip/ai-ide-setup" },
    { title: "Hylios", cat: "Mobile", img: ghibli("hylios"), one: "A published iOS game.", desc: "Published iOS game in the Ethereal Dimension universe — SpriteKit, hand-crafted visuals.", tech: ["Swift", "SpriteKit", "iOS"], link: "https://apps.apple.com/us/app/hylios/id6474466548" },
    { title: "Rosicrucian Vowel Sounds", cat: "Mobile", img: ghibli("rosicrucian-vowel-sounds"), one: "A published vocal-practice app.", desc: "Flutter app published on App Store & Play Store for guided vocal practice.", tech: ["Flutter", "Dart", "Audio"], link: "https://apps.apple.com/us/app/rosicrucian-vowel-sounds/id6529521816" },
    { title: "Rosicrucian Parenting", cat: "Mobile", img: ghibli("rosicrucian-parenting"), one: "A parenting platform, web + mobile.", desc: "Full-stack parenting platform with native iOS & Android apps serving thousands.", tech: ["Flutter", "iOS", "Android"], link: "https://rosicrucian-parenting.org/" },
    { title: "Voice Practice Hub", cat: "Tools", img: ghibli("voice-practice-hub"), one: "Guided voice training in the browser.", desc: "Audio-powered voice training with structured lessons and real-time feedback.", tech: ["React", "Web Audio API"], link: "https://voice-practice-hub.vercel.app/" },
    { title: "Audio Dialogues", cat: "AI/ML", img: ghibli("audio-dialogues"), one: "Talk with AI, out loud.", desc: "Interactive AI audio conversations with natural speech synthesis.", tech: ["React", "Audio API", "AI"], link: "https://audio-dialogues.vercel.app" },
    { title: "Ethereal Search Showcase", cat: "AI/ML", img: ghibli("ethereal-search"), one: "Search, reimagined with AI.", desc: "Next-gen AI search experience with semantic clustering and knowledge graphs.", tech: ["React", "Next.js", "AI Search"], link: "https://etherealsearch-showcase.vercel.app" },
    { title: "Cycles of Fate", cat: "Creative", img: ghibli("cycles-of-fate"), one: "Generative art about destiny.", desc: "Dynamic web experience exploring fate and cosmic cycles through generative visuals.", tech: ["React", "Generative Art"], link: "https://cycles-of-fate.vercel.app/" },
    { title: "Geometric Graph Design", cat: "Creative", img: ghibli("geometric-graph"), one: "Sacred geometry, generated live.", desc: "Generative geometric visualizations from mathematical algorithms — sacred geometry.", tech: ["React", "Canvas", "Math"], link: "https://v0-geometric-graph-design.vercel.app/" },
    { title: "Artful Archives", cat: "Creative", img: ghibli("artful-archives"), one: "A gallery that loads beautifully.", desc: "Performance-optimized creative showcase with fluid animations and lazy loading.", tech: ["React", "Animation"], link: "https://artful-archives-website.vercel.app" },
    { title: "Gurduwara Langar Game", cat: "Community", img: ghibli("gurduwara-langar-game"), one: "Sikh heritage, taught through play.", desc: "Gamified Sikh heritage app teaching community service — an ERG impact project.", tech: ["React Native", "Gamification"], github: "https://github.com/Ripnrip/GurduwaraLangarGame" },
  ],
};
