// Portfolio data — Gurinder Singh · H1 FY2026 (Dec 2025 – Jun 2026)
// Ghibli art + hackathon videos streamed from the live repo CDN.
const CDN = "https://raw.githubusercontent.com/Ripnrip/guriboycodes-portfolio/claude-portfolio/public";
const ghibli = (slug) => `${CDN}/images/projects/${slug}-ghibli.png`;
const vid = (file) => `assets/videos/${file}`;

window.PORTFOLIO_DATA = {
  cdn: CDN,
  hero: {
    name: "Gurinder Singh",
    handle: "guriboycodes",
    title: "Sr. Staff Applied AI Engineer · Mobile & AI",
    location: "New York, NY",
    period: "2020 — Present",
    pitch: "I build the AI infrastructure that lets autonomous programs ship.",
    typed: [
      "I build the platforms other engineers ship on.",
      "I turn emerging AI into products used by 90M+.",
      "iOS architecture, meet applied AI.",
    ],
    pitchAlt: "A decade turning prototypes into products used by 90M+ — iOS platform architecture and applied-AI systems at PayPal / Venmo. Patent holder, Official Bar Raiser, two-time hackathon winner.",
    portrait: "assets/me-ghibli.png",
    portraitAlt: "assets/me-paragliding.jpeg",
  },

  stats: [
    { value: "90M+", label: "Users impacted" },
    { value: "11", label: "Years shipping" },
    { value: "28+", label: "Hackathons" },
    { value: "2×", label: "First-place wins" },
    { value: "6+", label: "Countries" },
    { value: "1", label: "Patent holder" },
  ],

  flagship: [
    {
      id: "maia",
      cover: "ghibli-maia",
      image: "assets/covers/maia.jpg",
      codename: "MAIA × Venmo",
      title: "Cold-start to a unified PayPal program",
      tagline: "An AI agent that takes a new merchant from sign-up to live in about 20 minutes — work that used to take roughly three months.",
      status: "Productionized",
      stamp: "Now in live cohort pilots",
      window: "Apr 10 → Jun 26, 2026",
      sponsor: "Migration & Upgrade Program lead · MAIA PM · my manager",
      story: "I built an autonomous agent that walks a merchant through onboarding end to end. Over one weekend I grew the test set from 332 to 9,513 real businesses so the team finally had real-world ground truth, then demoed it live to 14 senior leaders: two real storefronts upgraded and accepting Venmo in about 20 minutes, on stage.",
      midyear: "May–Jun: named to the MAIA build core (Jun 8). The standalone Venmo working group folded into the single Migration & Upgrade Program (Jun 26) — \"plug Venmo into the one MAIA roadmap you own.\" Now moving from demo to first contained live cohort pilots.",
      stack: ["LLM Agents", "RAG", "D3.js", "CommonCrawl", "AWS Athena", "Remotion"],
      metrics: [
        { k: "Onboarding", v: "~3 mo → 20 min" },
        { k: "Businesses scored", v: "9,513" },
        { k: "Live demo", v: "to 14 leaders" },
        { k: "Status", v: "In production" },
      ],
      accent: "cyan",
    },
    {
      id: "darwin",
      cover: "ghibli-darwin",
      image: "assets/covers/darwin.jpg",
      codename: "Darwin",
      title: "Evolution framework, now productionized",
      tagline: "A system that improves AI skills on its own — and records every attempt, so it learns from its own history.",
      status: "Productionized",
      stamp: "Org home + CI · AI Labs onboard",
      window: "2026 · #1 May next-step, delivered",
      sponsor: "AI Toolkit lead · AI Labs",
      story: "If a task has a prompt going in, an answer coming out, and a way to score that answer, Darwin can improve it automatically: try many variations, keep the best, and open a pull request with the upgrade. Every attempt is saved with its score and the reasoning behind it, so each round builds on the last. It plugs into any code repository with no setup.",
      midyear: "Now invokable from any repo three ways (no fork) — reusable workflow, composite action, repository_dispatch. PR-gate auto-runs and posts a score-delta sticky comment. First clean end-to-end Bloom PR landed (#45 → #46). ~120 evolution runs against the real Pay-with-Venmo skill registry. Lives in PayPal-Venmo org with CI (DPEIR-4171).",
      stack: ["GEPA", "DSPy", "Cosmos", "Graph DB", "GitHub Actions"],
      metrics: [
        { k: "What it does", v: "Self-improves AI skills" },
        { k: "Upgrades shipped", v: "71 pull requests" },
        { k: "Variations tested", v: "1,020" },
        { k: "Setup needed", v: "None — any repo" },
      ],
      vocabulary: ["Seed", "Zephyr", "Polaris", "Compass", "Bloom", "Fossil", "Garden", "Gardener"],
      accent: "amber",
    },
    {
      id: "vireo",
      cover: "ghibli-vireo",
      image: "assets/covers/vireo.jpg",
      codename: "Vireo",
      title: "Telemetry + memory for AI dev workflows",
      tagline: "A flight recorder for AI agents — it captures everything they do, then remembers it.",
      status: "Production · v2",
      stamp: "Devmo §7 + §8 owner",
      window: "2026 ongoing",
      sponsor: "Devmo platform team · Venmo AI Council",
      story: "AI agents are hard to trust because you can't see what they actually did. Vireo records their actions from four different entry points and distills the logs into a memory the next run can draw on. It installs in two minutes and became the team's standard for watching agents in production.",
      midyear: "v2 shipped: RAG, per-sub-agent telemetry, and a unified OpenInference → OpenTelemetry export (Devmo PRs #128/#165) so Livery / Datadog / Langtrace can consume the stream. Memory-stack v2 is a cross-language Python + Swift hybrid. Captured a full MAIA run end-to-end: 53 events, 45 traces, 40 tool calls, 100% success in ~8 min.",
      stack: ["MCP", "n8n", "OpenTelemetry", "OpenInference", "Python", "Swift"],
      metrics: [
        { k: "What it is", v: "AI flight recorder" },
        { k: "Captures from", v: "4 entry points" },
        { k: "Adopted as", v: "team standard" },
        { k: "Install", v: "2 minutes" },
      ],
      accent: "emerald",
    },
    {
      id: "cosmos",
      cover: "ghibli-cosmos",
      image: "assets/covers/cosmos.jpg",
      codename: "claude-cosmos",
      title: "The universal LLM capture layer",
      tagline: "One safe doorway every AI request passes through — scrubbing sensitive data before it ever leaves.",
      status: "Live in prod",
      stamp: "The surface Vireo can't reach",
      window: "Q1–Q2 2026",
      sponsor: "Devmo · AI Toolkit lead",
      story: "When dozens of internal tools all talk to AI models, that traffic needs a single safe doorway. claude-cosmos is it: every request routes through one place, gets stripped of personal data, and is logged for safety. It covers the hosted and third-party tools that a local recorder like Vireo can't see.",
      midyear: "Now the network-layer telemetry path for MAIA (DTVZ-506) and the safe substrate that let external-agent (Hermes) research run isolated — as InfoSec/CDC confirmed in June. Used by Osaurus, Hermes Agent, Agent-0, Cosmos-IDE, and the Devmo webapp.",
      stack: ["Anthropic API", "MCP", "PII Scrubbing", "Cosmos"],
      metrics: [
        { k: "What it is", v: "Safe AI gateway" },
        { k: "Protects", v: "PII before it leaves" },
        { k: "In production", v: "6+ tools" },
      ],
      accent: "violet",
    },
    {
      id: "miam",
      cover: "ghibli-mac",
      image: "assets/covers/nested-silicon.jpg",
      codename: "Nested Silicon",
      title: "PayPal's first macOS-in-macOS substrate",
      tagline: "Running a Mac inside a Mac to make the iOS test suite 3× faster — on the same hardware.",
      status: "In active handoff",
      stamp: "iOS leadership sponsor signed",
      window: "Foundation · Q1 2026",
      sponsor: "iOS leadership · senior eng director · Livery lead",
      story: "iOS test runs were painfully slow. I was the first at the company to run a macOS virtual machine inside a macOS host, which let the test suite run in parallel. The first result: a run that took 22m 38s finished in 7m 23s — three times faster, on the same laptops, with no changes to the tests themselves.",
      midyear: "Became the runtime substrate Livery and Agent-0 both run on, and the VM-isolated containment that let Hermes research run safely (CDC-confirmed June). iOS sponsor signed May 5: \"I love it; I am sold on the performance.\" Operational ownership handing off to the iOS team + a peer engineer via lume.",
      stack: ["Virtualization.framework", "tart", "lume", "macOS", "Swift"],
      metrics: [
        { k: "iOS test suite", v: "22:38 → 7:23" },
        { k: "Speed", v: "3× faster" },
        { k: "New hardware", v: "none" },
      ],
      accent: "rose",
    },
  ],

  // Mid-year "also shipped" — joy & polish + platform extras
  shipped: [
    { name: "video-toolkit", desc: "New shared repo — Remotion 4.0 + Google Veo / Chirp3-TTS pipeline for explainer videos, podcasts, and per-PR narrated demo clips. Runs from GitHub Actions, no local setup.", tag: "New · open-sourced internally" },
    { name: "Devmo Prompt Enhancer + Guardrails", desc: "Two beta PRs migrated into the canonical Devmo repo (#59 Guard Rails, #60 Prompt Enhancer). Guardrails ship with ~90 tests including a prompt-injection battery.", tag: "Productionized" },
    { name: "DX Sounds", desc: "MCP server merged into the PayPal AI Hub — 8 themes, 14 tools. Sonic confetti for your dev loop.", tag: "In AI Hub" },
    { name: "Hermes security exchange", desc: "Turned an InfoSec flag into a voluntary full accounting (99.88% traffic on internal proxy, 12 sessions enumerated) — elevated agent-evolution work to the enterprise AI-tools evaluation.", tag: "Enterprise input" },
    { name: "\"Most Fun with AI\" talk", desc: "Mar 6 talk that launched FunAI Hack Hour as a recurring forum. Author of the Soul Stack (SOUL.md + STYLE.md + SKILL.md) pattern.", tag: "Talk · recurring forum" },
    { name: "Mercury 2025 / Hackathon-2025", desc: "The autonomous-merchant blueprint (Jul–Aug 2025) that turned out to be the imagination doc for everything in H1 FY2026.", tag: "The seed doc" },
  ],

  // Pre-built RAG knowledge base for "Ask My Brain"
  brain: {
    nodes: [
      { id: "maia", label: "MAIA × Venmo", kind: "system", x: 0.5, y: 0.3 },
      { id: "vireo", label: "Vireo", kind: "system", x: 0.25, y: 0.5 },
      { id: "cosmos", label: "claude-cosmos", kind: "system", x: 0.75, y: 0.5 },
      { id: "darwin", label: "Darwin", kind: "system", x: 0.3, y: 0.75 },
      { id: "miam", label: "Mac-in-a-Mac", kind: "system", x: 0.7, y: 0.75 },
      { id: "merchants", label: "9,513 merchants", kind: "metric", x: 0.55, y: 0.15 },
      { id: "devmo", label: "Devmo", kind: "program", x: 0.5, y: 0.55 },
      { id: "agent0", label: "Agent-0", kind: "system", x: 0.85, y: 0.7 },
      { id: "livery", label: "Livery", kind: "program", x: 0.85, y: 0.85 },
      { id: "fossils", label: "1,020 Fossils", kind: "metric", x: 0.15, y: 0.85 },
      { id: "gepa", label: "GEPA + DSPy", kind: "tech", x: 0.1, y: 0.65 },
      { id: "mcp", label: "MCP", kind: "tech", x: 0.15, y: 0.35 },
      { id: "otel", label: "OTel export", kind: "tech", x: 0.4, y: 0.4 },
      { id: "video", label: "video-toolkit", kind: "tech", x: 0.62, y: 0.68 },
      { id: "venmo", label: "Venmo (90M users)", kind: "program", x: 0.5, y: 0.92 },
    ],
    edges: [
      ["maia", "vireo"], ["maia", "cosmos"], ["maia", "merchants"],
      ["vireo", "devmo"], ["vireo", "mcp"], ["vireo", "cosmos"], ["vireo", "otel"],
      ["cosmos", "agent0"], ["cosmos", "devmo"],
      ["darwin", "gepa"], ["darwin", "fossils"], ["darwin", "cosmos"], ["darwin", "video"],
      ["miam", "agent0"], ["miam", "livery"],
      ["agent0", "livery"], ["maia", "venmo"], ["maia", "video"], ["otel", "livery"],
    ],

    corpus: [
      { id: "k1", topic: "MAIA", text: "MAIA × Venmo went from a 4-step AIM pipeline (aim_init_check → aim_convert_router → aim_correction → aim_paypal_ft) to a 20-minute live executive demo on April 29, 2026 in Austin. Took 84–89 days of Venmo onboarding to 20 minutes on stage, upgrading two real merchant sites V5 → V6 and enabling Venmo." },
      { id: "k2", topic: "MAIA", text: "Over one weekend (Apr 14) I scaled the test corpus from 332 → 9,513 scored US merchants across 18 independent harvest campaigns (CommonCrawl + AWS Athena + specialty hunters like enterprise_hunter, legacy_hunter, mega_r2). Identified 476 prime Venmo V1 candidates in the bullseye. Singapore's MAIA team had zero real-world telemetry; I gave them ground truth." },
      { id: "k3", topic: "MAIA", text: "On May 4, 2026 the program lead unified the program: Venmo upgrade should not be a separate track. By June 26 the standalone Venmo working group folded into the single PayPal Migration & Upgrade Program. On June 8 the MAIA PM named me to the MAIA build core. Now moving from demo to first contained live cohort pilots." },
      { id: "k4", topic: "Darwin", text: "Darwin is an evolution framework: anything with a prompt in, an output out, and a judge that can score it is GEPA-evolvable. Loop: Evolve → Evaluate → Preserve → Explain → Open PR. Regressions are not failure; they are scientific signal. Vocabulary: Seed, Zephyr, Polaris, Compass, Bloom, Fossil, Garden, Gardener." },
      { id: "k5", topic: "Darwin", text: "Darwin productionized in mid-2026: invokable from any repo three ways with no fork (reusable workflow, composite action, repository_dispatch). PR-gate auto-runs on any skill change and posts a score-delta sticky comment. First clean end-to-end Bloom PR landed (#45 → #46). ~120 evolution runs against the real Pay-with-Venmo skill registry. Now lives in the PayPal-Venmo org with CI (DPEIR-4171)." },
      { id: "k6", topic: "Darwin", text: "Output: 71 PRs across two milestones (37 + 34). Every PR ships a narrated video, score table, candidate arena, judge prompt, eval dataset, and full diff. The fossil record is a graph DB with full-text search: 1,020 candidates, 19 judges, 678 eval examples, cross-milestone lineage. Doctrinally aligned with NousResearch's hermes-agent-self-evolution and Imbue's Darwinian Evolver." },
      { id: "k7", topic: "Vireo", text: "Vireo is agent-agnostic event capture across four surfaces (MCP server, CLI vireo-send, shell hooks, skill instructions) feeding a 33-field schema into an n8n pipeline. Distills hourly into five memory kinds: procedural, failure, preference, semantic, episodic. 2-minute install via ./start.sh. Owns Devmo Workstreams §7 (Telemetry) + §8 (Memory)." },
      { id: "k8", topic: "Vireo", text: "Vireo v2 shipped RAG, per-sub-agent telemetry, and a unified OpenInference + OpenTelemetry export (Devmo PRs #128/#165) so Livery, Datadog, and Langtrace can consume the stream. Memory-stack v2 is a cross-language Python + Swift hybrid. Captured a full MAIA run end-to-end on May 15: 53 events, 45 traces, 40 tool calls, 10 skill events, 100% success in ~8 min." },
      { id: "k9", topic: "claude-cosmos", text: "claude-cosmos is a Claude-flavored proxy routing any Anthropic-shape request to PayPal's Cosmos LLM endpoints, with PII scrubbing, sanitization, and telemetry built into the proxy itself. It's the capture surface Vireo's hooks can't reach: hosted, ephemeral, and third-party agents. Used by Osaurus, NousResearch Hermes Agent, Agent-0, Cosmos-IDE, and the Devmo webapp." },
      { id: "k10", topic: "claude-cosmos", text: "The frame: Vireo catches what an agent intends to do on local CLI/IDE; claude-cosmos catches what every agent actually says to the model over the wire. Every call has to come through it to reach Cosmos at all, so capture is automatic and uniform — sanitization and PII scrub live in one place. It's now MAIA's network-layer telemetry path (DTVZ-506)." },
      { id: "k11", topic: "Mac-in-a-Mac", text: "Mac-in-a-Mac: PayPal's first macOS guest VM running inside a macOS host (Apple's Virtualization.framework + cirruslabs/tart). First measured result: PayWithVenmo plan 22m 38s → 7m 23s (3.0× speedup) on existing hardware — no cloud, no new minis, no test modifications. Now the runtime substrate Livery and Agent-0 both run on. iOS sponsor signed May 5: 'I am sold on the performance.'" },
      { id: "k12", topic: "Mac-in-a-Mac", text: "The Mac-in-a-Mac VM also provided the sanctioned, isolated containment that let me run external-agent (Hermes) research safely, as CDC/InfoSec confirmed in June. Every iOS team can shard test plans across host + 1–2 child VMs per Mac mini: 120-test suites become 3 shards of 40 running in parallel. Operational ownership is handing off to the iOS team and a peer engineer via lume." },
      { id: "k13", topic: "Mid-year", text: "Since the May checkpoint: Darwin productionized, Vireo v2, the MAIA track folded into one program moving to live pilots, a new shared video-toolkit repo (Remotion 4.0 + Google Veo / Chirp3-TTS, runs from GitHub Actions), and a Hermes security-review exchange that elevated the agent-evolution work to the enterprise AI-tools evaluation." },
      { id: "k14", topic: "Mid-year", text: "Devmo Prompt Enhancer + Guardrails migrated into the canonical Devmo repo (PRs #59 Guard Rails, #60 Prompt Enhancer); guardrails ship with ~90 tests including a prompt-injection battery. Also raised a skill supply-chain safety policy ('no URLs in skills') after ~820 malicious skills were found in a public hub." },
      { id: "k15", topic: "Scope", text: "Scope expansion: started December 2025 as iOS Sandbox DRI on Pay With Venmo (TestFlight pipeline, Ladybug debug menu, daily E2E call ownership). By June 2026: owner of the Vireo telemetry + memory layer, originator of Mac-in-a-Mac, architect of Darwin, and named to the MAIA build core. The work crosses 3 BUs (Venmo, SMB-FS, LE/GSA), sponsored at Senior Director / VP-adjacent level." },
      { id: "k16", topic: "Venmo", text: "Earlier iOS impact at Venmo: QRC Widget Patent (2022) — first team to use SwiftUI for iOS widgets at Venmo, reduced user friction by 66%. Dynamic Island / Live Activities / App Clip infrastructure. Pay With Venmo Checkout cut pay-sheet render latency by ~2 seconds. Gift Cards for Amazon and Starbucks. QRC moonshot led to a $60M CVS contract; Amex partnership for a $400M deal." },
      { id: "k17", topic: "Hackathons", text: "28+ hackathons across 6+ countries. Two first-place wins: MLH @ Bloomberg London 2017 (Automated Search & Rescue System, featured in a BBC documentary) and Devcamp NYC 2016 (Talent Management App, won among 300+ at Google NYC). HackZurich 2018 finalist (AR Car Buying Tool, top of 400+). Judge twice at Hack Yale." },
      { id: "k18", topic: "Philosophy", text: "Human-centered applied AI: elevate human skill, judgment, and ethos through careful system design. The 'Stay to the plan' hook is a 20-line markdown file that solves the same problem people throw 20K-token prompts at — a deterministic ring around multi-sub-agent autonomy. Most of the logic lives in markdown, not code: a glimpse of what the future of coding looks like." },
      { id: "k19", topic: "Philosophy", text: "Three principles: (1) Platform over features — build the substrate (telemetry, proxies, evolution frameworks) that lets others ship. (2) Observability as architecture — Vireo catches intent locally, claude-cosmos catches every call over the wire; together that's total coverage. (3) Ship then evolve — regressions are scientific signal, not failure, proven by Darwin's 1,020-candidate fossil record." },
      { id: "k20", topic: "Hackathons", text: "Hackathon film reel: MLH Prime 2017 in London (Bloomberg) won 1st place with a DJI-drone Search & Rescue system using IBM Watson facial recognition, featured in a BBC documentary. HackZurich 2022 won 1st place with 'Elate' (sponsored by Schindler). HackZurich 2021 was a solo build, ARon — an AR fitness coach using CreateML + ARKit pose detection with Garmin integration. There are videos of all three." },
      { id: "k21", topic: "Leadership", text: "Official Bar Raiser at PayPal/Venmo: 500+ technical interviews across iOS, system design, and AI/ML; final decision-maker on critical hiring rounds; mentored 20+ engineers to promotion. Interfaith ERG Chapter Lead for the Sikh community (founded, grew to 150+ members globally). Judge twice at Hack Yale, mentor at PennApps, advisory board at Bayside High School's CTE program." },
      { id: "k22", topic: "Side projects", text: "Beyond PayPal: Flow (Dynamic Island iOS app), Ethereal Dimension (AI storytelling platform with Three.js worlds), Zai Vision Suite (GLM-4.6V computer vision), a RAG Rosicrucian Knowledge Explorer, Agentic News Transformer (LangChain + CrewAI), published App Store apps (Hylios game, Rosicrucian Vowel Sounds), and open-source dev tools (TweakCC for Claude Code, CodeFlow architecture maps, Scarf — a native Hermes agent GUI)." },
      { id: "k23", topic: "Scope", text: "Working style: I gravitate to the load-bearing substrate nobody else owns yet, get named senior sponsorship fast, and hand off cleanly once it's productionized (Mac-in-a-Mac to the iOS team, Darwin to AI Labs). I narrate everything — D3 knowledge graphs, Remotion explainer videos, score-delta PR comments — so the work is legible to leaders, not just other engineers." },
      { id: "k24", topic: "Hire", text: "Why hire Gurinder: in one half-year he authored five productionized, cross-BU AI-platform systems with VP-adjacent sponsorship, took 84–89-day merchant onboarding to a 20-minute executive demo, and delivered a 3.0× iOS test speedup — while also being an Official Bar Raiser (500+ interviews) and a patent holder. He builds platforms others ship on, communicates impact to leadership, and turns ambiguous greenfield into named, sponsored, handed-off infrastructure." },
    ],

    examples: [
      "What's MAIA and why does it matter?",
      "How did Darwin get productionized?",
      "What's new in Vireo v2?",
      "What's it like to work with Gurinder?",
      "Tell me about the hackathon wins",
      "Why should we hire him?",
    ],
  },

  experience: [
    {
      company: "PayPal / Venmo",
      role: "Staff iOS Engineer → Sr. Staff Applied AI/ML Engineer",
      window: "2019 — Present",
      logo: "assets/logos/paypal.svg",
      logoAlt: "assets/logos/venmo.png",
      bullets: [
        "Authored five production AI-platform systems — MAIA, Vireo, claude-cosmos, Darwin, and Nested Silicon — turning AI prototypes into canonical platform programs adopted across the org.",
        "Scaled Venmo iOS features to 92M+ active users and closed a $60M enterprise contract in year one.",
        "QRC Widget patent holder — first SwiftUI iOS widget at Venmo, cutting user friction 66%; shipped Venmo Gift Cards (Amazon, Starbucks) and Pay With Venmo for JetBlue.",
        "Official Bar Raiser — 500+ technical interviews; built cross-team AI enablement forums and mentored engineers into responsible agentic workflows.",
      ],
    },
    {
      company: "Google Stadia",
      role: "iOS Developer / Consultant",
      window: "2018 — 2019",
      logo: "assets/logos/stadia.png",
      bullets: [
        "Supported launch readiness for Stadia cloud gaming on mobile — Flutter/Dart with native iOS plugins.",
        "Implemented low-latency Core Bluetooth controller connectivity.",
        "Profiled CPU/GPU with Xcode Instruments to improve launch-quality stability.",
      ],
    },
    {
      company: "Morgan Stanley",
      role: "iOS Engineer",
      window: "2016 — 2018",
      logo: "assets/logos/morgan-stanley.png",
      bullets: [
        "Modernized Wealth Management mobile experiences for ultra-high-net-worth clients.",
        "Built check-deposit, biometric auth, certificate-pinning, and jailbreak detection.",
        "Migrated core iOS code from Objective-C toward Swift atop hybrid Cordova infrastructure.",
      ],
    },
  ],

  hackathonStats: [
    { value: "28+", label: "Hackathons" },
    { value: "6+", label: "Countries" },
    { value: "2", label: "First-place wins" },
    { value: "2×", label: "Judged at Yale" },
  ],

  // lat/lng markers for the globe — cities on the hackathon circuit
  hackathonMarkers: [
    { location: [51.5074, -0.1278], size: 0.10, label: "London 🇬🇧" },
    { location: [40.7128, -74.006], size: 0.11, label: "New York 🇺🇸" },
    { location: [47.3769, 8.5417], size: 0.10, label: "Zurich 🇨🇭" },
    { location: [41.3874, 2.1686], size: 0.07, label: "Barcelona 🇪🇸" },
    { location: [55.6761, 12.5683], size: 0.06, label: "Copenhagen 🇩🇰" },
    { location: [37.7749, -122.4194], size: 0.07, label: "San Francisco 🇺🇸" },
    { location: [35.6762, 139.6503], size: 0.07, label: "Tokyo 🇯🇵" },
  ],

  hackathons: [
    { place: "1st", year: "2017", name: "MLH Prime — Bloomberg London", flag: "🇬🇧", img: "assets/hackathons/drone-sar.png", desc: "Automated Search & Rescue — DJI drones + IBM Watson facial recognition. Featured in a BBC documentary.", win: true },
    { place: "1st", year: "2022", name: "HackZurich — Schindler Group", flag: "🇨🇭", desc: "\"Elate\" — winning hack built with a 5-person team at HackZurich.", win: true },
    { place: "1st", year: "2016", name: "Devcamp NYC — Google NYC", flag: "🇺🇸", desc: "Talent Management App — first place among 300+ participants at Google NYC.", win: true },
    { place: "Solo", year: "2021", name: "HackZurich — ARon", flag: "🇨🇭", img: "assets/hackathons/aron.png", desc: "AR fitness coach — CreateML + ARKit pose detection with Garmin biometrics." },
    { place: "Finalist", year: "2018", name: "HackZurich — Carly", flag: "🇨🇭", img: "assets/hackathons/carly.png", desc: "Voice-controlled AR car configurator with Credit Suisse API. Top of 400+." },
    { place: "Team", year: "2023", name: "HackZurich — Legal Lunatics", flag: "🇨🇭", desc: "Implenia-sponsored build with a returning 5-person crew." },
    { place: "Impact", year: "2025", name: "Agentic SEO", flag: "🇺🇸", desc: "Agent-driven SEO pipeline — hackathon energy pointed at a live, deployed tool." },
    { place: "Impact", year: "—", name: "Gurduwara Langar Game", flag: "🧡", img: ghibli("gurduwara-langar-game"), desc: "Sikh heritage taught through play — an ERG community build in the same weekend spirit." },
    { place: "Judge", year: "2022", name: "Hack Yale (2×)", flag: "🇺🇸", desc: "Evaluated technical feasibility & innovation for 500+ participants." },
    { place: "Mentor", year: "—", name: "PennApps — UPenn", flag: "🇺🇸", desc: "Mentored students through complex mobile & AI implementations." },
    { place: "Conf", year: "—", name: "try! Swift Tokyo", flag: "🇯🇵", desc: "iOS community conference in Tokyo — plugged into the global Swift network." },
  ],

  // Full skill catalog — group / color / icon / proficiency.
  // Feeds both the Skills section AND the Ask-My-Brain knowledge graph (icon nodes).
  skills: [
    {
      group: "AI / ML & Agents",
      key: "ai",
      accent: "violet",
      items: [
        { name: "Python", icon: "assets/tech/python.svg", level: 96 },
        { name: "Claude", icon: "assets/tech/claude.svg", level: 96 },
        { name: "OpenAI", icon: "assets/tech/openai.svg", level: 94 },
        { name: "Gemini", icon: "assets/tech/gemini.png", level: 92 },
        { name: "Ollama", icon: "assets/tech/ollama.svg", level: 88 },
        { name: "LangChain", icon: "assets/tech/langchain.svg", level: 93 },
        { name: "LangGraph", icon: "assets/tech/langgraph.svg", level: 88 },
        { name: "LlamaIndex", icon: "assets/tech/llamaindex.png", level: 86 },
        { name: "CrewAI", icon: "assets/tech/crewai.svg", level: 85 },
        { name: "MCP", icon: "assets/tech/mcp.svg", level: 95 },
        { name: "DSPy / GEPA", icon: "assets/tech/python.svg", level: 90 },
        { name: "RAG Pipelines", icon: "assets/tech/rag-pipelines.svg", level: 95 },
        { name: "PyTorch", icon: "assets/tech/pytorch.svg", level: 84 },
        { name: "MLX", icon: "assets/tech/mlx.svg", level: 86 },
        { name: "Stable Diffusion", icon: "assets/tech/stable-diffusion.svg", level: 82 },
        { name: "OpenCV", icon: "assets/tech/opencv.svg", level: 80 },
        { name: "Hugging Face", icon: "assets/tech/hugging-face.svg", level: 84 },
        { name: "Replicate", icon: "assets/tech/replicate.svg", level: 85 },
        { name: "TensorFlow", icon: "assets/tech/tensorflow.svg", level: 80 },
        { name: "OpenRouter", icon: "assets/tech/openrouter.svg", level: 85 },
        { name: "ElevenLabs", icon: "assets/tech/elevenlabs.svg", level: 86 },
      ],
    },
    {
      group: "Mobile / iOS",
      key: "mobile",
      accent: "cyan",
      items: [
        { name: "Swift", icon: "assets/tech/swift.svg", level: 96 },
        { name: "SwiftUI", icon: "assets/tech/swiftui.svg", level: 95 },
        { name: "Objective-C", icon: "assets/tech/objective-c.svg", level: 88 },
        { name: "ARKit", icon: "assets/tech/arkit.svg", level: 85 },
        { name: "RoomPlan", icon: "assets/tech/roomplan.png", level: 80 },
        { name: "CoreML", icon: "assets/tech/coreml.svg", level: 88 },
        { name: "ActivityKit", icon: "assets/tech/activitykit.svg", level: 95 },
        { name: "WidgetKit", icon: "assets/tech/widgetkit.png", level: 95 },
        { name: "MapKit", icon: "assets/tech/mapkit.svg", level: 88 },
        { name: "BLE / NFC", icon: "assets/tech/ble.svg", level: 88 },
        { name: "Xcode", icon: "assets/tech/xcode.svg", level: 94 },
        { name: "Flutter", icon: "assets/tech/flutter.svg", level: 82 },
        { name: "Dart", icon: "assets/tech/dart.svg", level: 80 },
        { name: "React Native", icon: "assets/tech/react-native.svg", level: 82 },
      ],
    },
    {
      group: "Cloud & DevOps",
      key: "cloud",
      accent: "emerald",
      items: [
        { name: "AWS", icon: "assets/tech/aws.svg", level: 90 },
        { name: "GCP", icon: "assets/tech/googlecloud.svg", level: 88 },
        { name: "Azure", icon: "assets/tech/azure.svg", level: 82 },
        { name: "Docker", icon: "assets/tech/docker.svg", level: 90 },
        { name: "GitHub Actions", icon: "assets/tech/github-actions.svg", level: 94 },
        { name: "Jenkins", icon: "assets/tech/jenkins.svg", level: 80 },
        { name: "Fastlane", icon: "assets/tech/fastlane.svg", level: 92 },
        { name: "Vercel", icon: "assets/tech/vercel.svg", level: 92 },
        { name: "Datadog", icon: "assets/tech/datadog.svg", level: 85 },
        { name: "Firebase", icon: "assets/tech/firebase.svg", level: 85 },
        { name: "RunPod", icon: "assets/tech/runpod.svg", level: 82 },
        { name: "n8n", icon: "assets/tech/n8n.svg", level: 90 },
      ],
    },
    {
      group: "Data & Tools",
      key: "data",
      accent: "amber",
      items: [
        { name: "PostgreSQL", icon: "assets/tech/postgresql.svg", level: 90 },
        { name: "MongoDB", icon: "assets/tech/mongodb.svg", level: 88 },
        { name: "Redis", icon: "assets/tech/redis.svg", level: 86 },
        { name: "Pinecone", icon: "assets/tech/pinecone.png", level: 92 },
        { name: "ChromaDB", icon: "assets/tech/chromadb.svg", level: 92 },
        { name: "Qdrant", icon: "assets/tech/qdrant.svg", level: 88 },
        { name: "Neo4j", icon: "assets/tech/neo4j.svg", level: 88 },
        { name: "GraphQL", icon: "assets/tech/graphql.svg", level: 84 },
        { name: "Next.js", icon: "assets/tech/nextjs.svg", level: 92 },
        { name: "React", icon: "assets/tech/react.svg", level: 92 },
        { name: "TypeScript", icon: "assets/tech/typescript.svg", level: 90 },
        { name: "NumPy", icon: "assets/tech/numpy.svg", level: 85 },
        { name: "Pandas", icon: "assets/tech/pandas.svg", level: 85 },
        { name: "Figma", icon: "assets/tech/figma.svg", level: 88 },
        { name: "GitHub", icon: "assets/tech/github.svg", level: 95 },
        { name: "Cursor", icon: "assets/tech/cursor.svg", level: 96 },
      ],
    },
  ],

  // Engineering philosophy — what it's like to build with me
  philosophy: {
    quote: "I build the AI infrastructure that lets autonomous programs ship.",
    principles: [
      { title: "Platform over features", body: "The most durable engineering is substrate — telemetry layers, proxy surfaces, evolution frameworks. I build the platforms that let others ship, not just point features." },
      { title: "Observability as architecture", body: "Vireo + claude-cosmos = total coverage. Intent captured locally, ground truth captured over the wire. Anywhere an LLM call can hide is a gap I close by design." },
      { title: "Ship, then evolve", body: "Darwin's fossil record proves it: regressions aren't failure, they're scientific signal. 71 PRs, 1,020 candidates — every failure informs the next bloom." },
    ],
  },

  // "What it's like to work with me" — the easter-egg video + hackathon film reel
  media: {
    workWithMe: {
      title: "What it's like to work with me",
      blurb: "A behind-the-scenes look — equal parts demo energy and dad jokes. Click the 👀 in the corner, or here.",
      file: vid("working-with-me.mp4"),
    },
    reel: [
      { title: "Drone Search & Rescue", event: "MLH Prime 2017 · Bloomberg London", place: "1st place", note: "Featured in a BBC documentary. DJI drones + IBM Watson facial recognition to locate stranded people.", file: vid("mlh-2017-drone-bbc.mp4"), flag: "🇬🇧" },
      { title: "Carly — AR Car Visualizer", event: "HackZurich 2018", place: "Finalist", note: "Voice-controlled AR car configurator — real-time 3D rendering, top of 400+ teams.", file: vid("hackzurich-ar.mp4"), flag: "🇨🇭" },
      { title: "ARon — AI Fitness Coach", event: "HackZurich 2021", place: "Solo build", note: "CreateML + ARKit real-time pose detection, Garmin biometric integration.", file: vid("hackzurich-2021-aron.mp4"), flag: "🇨🇭" },
    ],
  },

  // Icon lookup for bundle stack chips — only verified-on-disk assets.
  iconMap: {
    "Python": "assets/tech/python.svg",
    "Claude": "assets/tech/claude.svg",
    "OpenAI": "assets/tech/openai.svg",
    "LangChain": "assets/tech/langchain.svg",
    "CrewAI": "assets/tech/crewai.svg",
    "RAG": "assets/tech/rag-pipelines.svg",
    "Qdrant": "assets/tech/qdrant.svg",
    "Next.js": "assets/tech/nextjs.svg",
    "React": "assets/tech/react.svg",
    "ARKit": "assets/tech/arkit.svg",
    "RoomPlan": "assets/tech/roomplan.png",
    "CoreML": "assets/tech/coreml.svg",
    "Swift": "assets/tech/swift.svg",
    "SwiftUI": "assets/tech/swiftui.svg",
    "ActivityKit": "assets/tech/activitykit.svg",
    "WidgetKit": "assets/tech/widgetkit.png",
    "Flutter": "assets/tech/flutter.svg",
    "TypeScript": "assets/tech/typescript.svg",
    "React Native": "assets/tech/react-native.svg",
    "MCP": "assets/tech/mcp.svg",
  },

  // ============================================================
  // THE 15-BUNDLE MODEL — from the 2026-07-01 repo audit.
  // 295 local repos + 169 GitHub + 51 Vercel, curated down to 15.
  // readiness: ship-ready | public-demo | case-study | needs-media | needs-sanitization
  // punchlist: the media punch list per bundle (have/need).
  // Employer flagships (tier:"augment") keep their rich copy in `flagship`
  // above — entries here carry curation metadata only.
  // Toggle "Curation mode" in Tweaks to see readiness + punch lists in the UI.
  // ============================================================
  bundles: [
    {
      id: "maia", rank: 1, tier: "augment", kind: "employer",
      readiness: "case-study",
      why: "The highest-business-impact AI system in the portfolio — merchant onboarding taken from months to about 20 minutes, demoed live to leadership.",
      links: {},
      punchlist: { screenshot: "need", diagram: "need", gifVideo: "need", logoIcon: "have", publicUrl: "n/a", githubUrl: "n/a" },
      accent: "cyan",
      sanitizationNote: "Employer case study — selected details redacted. Visuals must be sanitized (no merchant names, internal tool UIs, or dashboards).",
    },
    {
      id: "darwin", rank: 2, tier: "augment", kind: "employer",
      readiness: "case-study",
      why: "The strongest autonomous-systems story: a self-improving skill engine with a PR-gated evolution loop.",
      links: {},
      punchlist: { screenshot: "need", diagram: "need", gifVideo: "need", logoIcon: "have", publicUrl: "n/a", githubUrl: "n/a" },
      accent: "amber",
      sanitizationNote: "Employer case study — selected details redacted. Demo GIFs must be recorded against a sanitized example repo, never the internal skill registry.",
    },
    {
      id: "vireo", rank: 3, tier: "augment", kind: "employer",
      readiness: "needs-media",
      why: "The infrastructure-backbone story: LLM observability and memory built as platform work, with public-adjacent observability repos to show for it.",
      links: { github: "https://github.com/artfularchivesstudio-spec/observability-swift-client" },
      punchlist: { screenshot: "need", diagram: "need", gifVideo: "need", logoIcon: "have", publicUrl: "need", githubUrl: "have" },
      accent: "emerald",
      sanitizationNote: "Employer case study — selected details redacted. Public surface is limited to the observability-* companion repos.",
    },
    {
      id: "agent0", rank: 4, tier: "full", kind: "personal",
      codename: "Agent Zero", title: "An AI agent with its own computer",
      readiness: "needs-media",
      one: "An agent with its own Mac.",
      tagline: "An open-source agent running inside its own macOS virtual machine — it does real work on a real computer, and messages me on WhatsApp.",
      story: "I gave an AI agent its own computer: the open-source Agent Zero framework running inside a dedicated macOS VM (Tart, 8 cores, 8 GB), safely walled off from my machine. It reaches me over WhatsApp, and I put it to work on the least fun job I know — the career pipeline: a multi-user job-search system with contact enrichment and outreach automation. It's the personal twin of the agent-isolation work I do professionally.",
      why: "Shows I can stand up, isolate, and operate autonomous agents on real machines — the same discipline as my platform work, on my own hardware.",
      stack: ["Agent Zero", "Python", "Tart VM", "macOS", "WhatsApp"],
      metrics: [
        { k: "Runs in", v: "its own macOS VM" },
        { k: "VM spec", v: "8 cores · 8 GB" },
        { k: "Reaches me via", v: "WhatsApp" },
      ],
      links: { github: "https://github.com/Ripnrip/agent-zero-macOS" },
      punchlist: { screenshot: "need", diagram: "need", gifVideo: "need", logoIcon: "need", publicUrl: "n/a", githubUrl: "have" },
      accent: "cyan",
      art: "assets/covers/bundles/agent0.svg",
      cover: "assets/covers/bundles/agent0.svg",
      foldsIn: [],
    },
    {
      id: "miam", rank: 5, tier: "augment", kind: "employer",
      readiness: "case-study",
      why: "A memorable Staff-level systems story: nested macOS virtualization delivering a measured 3× iOS test speedup on existing hardware.",
      links: {},
      punchlist: { screenshot: "need", diagram: "need", gifVideo: "need", logoIcon: "have", publicUrl: "n/a", githubUrl: "n/a" },
      accent: "rose",
      sanitizationNote: "Employer case study — selected details redacted. Diagram shows VM topology and measured before/after only — no internal CI project names.",
    },
    {
      id: "cosmos", rank: 6, tier: "augment", kind: "employer",
      readiness: "needs-media",
      why: "The connective tissue of the whole portfolio: one safe gateway — routing, PII scrubbing, telemetry — that every other AI system passes through.",
      links: {},
      punchlist: { screenshot: "have", diagram: "need", gifVideo: "need", logoIcon: "have", publicUrl: "need", githubUrl: "need" },
      accent: "violet",
      foldsIn: [{ n: "AI IDE Setup & Workflows" }],
      sanitizationNote: "Employer case study — selected details redacted. A public-safe repo/README must be scrubbed of internal endpoints and program names.",
    },
    {
      id: "rosicrucian", rank: 7, tier: "full", kind: "personal",
      codename: "Knowledge Explorer", title: "Centuries-old texts, answering with citations",
      readiness: "public-demo",
      one: "Ask centuries-old texts anything.",
      tagline: "A RAG search engine over 73K+ vectors of books, digests, podcasts, and video — with answers that cite their sources down to the page and the timestamp.",
      story: "I built a full-stack search engine for a community's library of esoteric texts and recordings: 73K+ vectors from books, digests, symposiums, podcasts, and YouTube. Ask a question and it answers with receipts — the PDF viewer jumps to the exact page and highlights it; the audio and video players seek to the exact moment. Around it I've shipped App Store apps for the same community, including a guided vowel-practice app and a parenting platform. It's my favorite proof that retrieval is only half the product — the other half is trust.",
      why: "A complete, public, end-to-end RAG product — retrieval, citation UX, a test suite, analytics — not a demo notebook.",
      stack: ["Python", "RAG", "Qdrant", "OpenAI", "Next.js"],
      metrics: [
        { k: "Corpus", v: "73K+ vectors" },
        { k: "Sources", v: "books · podcasts · video" },
        { k: "Tests", v: "60-test suite" },
        { k: "Citations", v: "page-jump + timestamp seek" },
      ],
      links: { demo: "https://rosicrucian-knowledge-explorer.vercel.app", appstore: "https://apps.apple.com/us/app/rosicrucian-vowel-sounds/id6529521816" },
      punchlist: { screenshot: "have", diagram: "need", gifVideo: "need", logoIcon: "need", publicUrl: "have", githubUrl: "need" },
      accent: "amber",
      art: ghibli("rosicrucian-knowledge-explorer"),
      cover: "assets/covers/bundles/rosicrucian.svg",
      foldsIn: [
        { n: "Rosicrucian Vowel Sounds", href: "https://apps.apple.com/us/app/rosicrucian-vowel-sounds/id6529521816" },
        { n: "Rosicrucian Parenting", href: "https://rosicrucian-parenting.org/" },
        { n: "Voice Practice Hub", href: "https://voice-practice-hub.vercel.app/" },
      ],
    },
    {
      id: "ethereal", rank: 8, tier: "full", kind: "personal",
      codename: "Ethereal Dimension", title: "One universe: stories, a game, an AR scanner",
      readiness: "needs-media",
      one: "An AI-built storytelling universe.",
      tagline: "A storytelling universe spanning a 3D web world, a published iOS game, and an AR room scanner that a city transportation department put to work.",
      story: "Ethereal Dimension started as an AI storytelling platform — interactive narratives inside Three.js worlds — and grew a real-world arm: an AR scanner built on RoomPlan and ARKit that captures spaces in 3D, plus a computer-vision system for real-time barricade detection built with the Austin Department of Transportation. The same universe shipped Hylios, a hand-crafted SpriteKit game on the App Store. It's where my creative work and my spatial-computing work live in one place.",
      why: "Proves range for an AI+iOS portfolio: ARKit/RoomPlan spatial computing, shipped App Store products, and a distinctive creative brand in one coherent world.",
      stack: ["Three.js", "React", "ARKit", "RoomPlan", "CoreML"],
      metrics: [
        { k: "Partner", v: "Austin DoT" },
        { k: "Scanner", v: "RoomPlan + ARKit" },
        { k: "On the App Store", v: "Hylios" },
      ],
      links: { demo: "https://etherealdimension.io", appstore: "https://apps.apple.com/us/app/hylios/id6474466548" },
      punchlist: { screenshot: "have", diagram: "need", gifVideo: "need", logoIcon: "need", publicUrl: "have", githubUrl: "need" },
      accent: "violet",
      art: ghibli("ethereal-dimension"),
      cover: "assets/covers/bundles/ethereal.svg",
      foldsIn: [
        { n: "Hylios", href: "https://apps.apple.com/us/app/hylios/id6474466548" },
        { n: "Ethereal Search Showcase", href: "https://etherealsearch-showcase.vercel.app" },
      ],
    },
    {
      id: "flow", rank: 9, tier: "full", kind: "personal",
      codename: "Flow", title: "Dynamic Island as a real product",
      readiness: "needs-media",
      one: "Dynamic Island, done beautifully.",
      tagline: "A productivity app that lives in the Dynamic Island — state-driven animation and deep system integration, with the code public.",
      story: "Flow is my love letter to the Dynamic Island: a productivity app whose whole interface lives up there, driven by state animations and deep system integration. At work I built Dynamic Island and Live Activities infrastructure for Venmo; Flow is where I push the same surface as far as it will go, in public, on my own terms.",
      why: "iOS product craft in its purest form — the system surface everyone has seen, executed with care, with public code to read.",
      stack: ["Swift", "SwiftUI", "ActivityKit", "WidgetKit"],
      metrics: [
        { k: "Surface", v: "Dynamic Island + Live Activities" },
        { k: "Code", v: "public on GitHub" },
      ],
      links: { github: "https://github.com/Ripnrip/Flow" },
      punchlist: { screenshot: "have", diagram: "need", gifVideo: "need", logoIcon: "need", publicUrl: "need", githubUrl: "have" },
      accent: "cyan",
      art: ghibli("flow"),
      cover: "assets/covers/bundles/flow.svg",
      foldsIn: [],
    },
    {
      id: "scrolltracker", rank: 10, tier: "full", kind: "personal",
      codename: "ScrollTracker", title: "Automation that checks its own work",
      readiness: "needs-sanitization",
      one: "Real surfaces, verified runs.",
      tagline: "A Swift automation system that drives real mobile and browser surfaces — and validates every run against what actually happened on screen.",
      story: "ScrollTracker is a private automation rig I keep sharpening: it operates real mobile and browser surfaces end to end, then verifies each run against the live surface instead of trusting its own logs. Building it has taught me more about real-world automation — timing, state drift, recovery — than any test suite, and that reliability discipline feeds straight back into my agent work. The code stays private; the case study is the capability.",
      why: "Hard-won, real-world automation and validation engineering — the unglamorous reliability work that trustworthy agent systems are made of.",
      stack: ["Swift", "Claude", "Automation"],
      metrics: [
        { k: "Status", v: "active — June 2026" },
        { k: "Validation", v: "against the live surface" },
      ],
      links: {},
      punchlist: { screenshot: "need", diagram: "need", gifVideo: "need", logoIcon: "need", publicUrl: "n/a", githubUrl: "need" },
      accent: "emerald",
      art: "assets/covers/bundles/scrolltracker.svg",
      cover: "assets/covers/bundles/scrolltracker.svg",
      foldsIn: [],
      sanitizationNote: "Held back on purpose: the repo stays private, and the public card names no automation targets, employers, platforms, or volumes — capability-level description only.",
    },
    {
      id: "papervault", rank: 11, tier: "full", kind: "personal",
      codename: "PaperVault", title: "The newest build on the bench",
      readiness: "needs-media",
      one: "A brand-new Swift app, mid-forge.",
      tagline: "An early-stage native Swift app — the most recently active repo in my workshop, still being shaped into a product.",
      story: "PaperVault is the freshest thing I'm building: a native Swift app early enough that the product framing is still in motion. It's where my commits are landing right now — July 2026 — and it gets its public unveiling once the README, screenshots, and story are worthy of it. Watch this space.",
      why: "Signals a live personal build cadence — still shipping greenfield Swift on my own time, a decade in.",
      stack: ["Swift"],
      metrics: [
        { k: "Status", v: "in active development" },
        { k: "Latest commit", v: "July 2026" },
      ],
      links: {},
      punchlist: { screenshot: "need", diagram: "need", gifVideo: "need", logoIcon: "need", publicUrl: "n/a", githubUrl: "need" },
      accent: "amber",
      art: "assets/covers/bundles/papervault.svg",
      cover: "assets/covers/bundles/papervault.svg",
      foldsIn: [],
    },
    {
      id: "my4blocks", rank: 12, tier: "full", kind: "personal",
      codename: "My4Blocks", title: "Emotional skills, taught in blocks",
      readiness: "needs-sanitization",
      one: "Feelings, taught like building blocks.",
      tagline: "An emotional-education platform — the 'four blocks' — spanning a web app, a mobile app, and retrieval that answers from the actual curriculum.",
      story: "My4Blocks teaches emotional skills the way you'd teach anything else: in small, buildable blocks. It spans a web app, a mobile app, and a RAG layer so answers come from the source material rather than a model's vibes — including experiments with PageIndex-style retrieval that navigates a document's structure the way a person would. It's the project where my AI work gets to serve something soft.",
      why: "AI applied to human development — curriculum-grounded RAG across web and mobile, with the judgment to keep private things private.",
      stack: ["Next.js", "Flutter", "RAG", "PageIndex"],
      metrics: [
        { k: "Surfaces", v: "web · mobile · RAG" },
        { k: "Retrieval", v: "PageIndex experiments" },
      ],
      links: { demo: "https://my4blocks.vercel.app" },
      punchlist: { screenshot: "need", diagram: "need", gifVideo: "need", logoIcon: "need", publicUrl: "have", githubUrl: "need" },
      accent: "cyan",
      art: "assets/covers/bundles/my4blocks.svg",
      cover: "assets/covers/bundles/my4blocks.svg",
      foldsIn: [],
      sanitizationNote: "Repo stays private pending the privacy check — content and data must be confirmed public-safe before any repo link ships. The Vercel demo is the curated public route.",
    },
    {
      id: "artful", rank: 13, tier: "full", kind: "personal",
      codename: "Artful Archives", title: "A studio brand run like a product",
      readiness: "needs-media",
      one: "A gallery that loads beautifully.",
      tagline: "An art-studio brand with real infrastructure behind it: a performance-tuned gallery site, a Swift-based CMS, and its own VPS backend.",
      story: "Artful Archives Studio is a creative brand I run like a real product: a performance-optimized gallery site with fluid animations and lazy loading, a Swift-based CMS, and a VPS backend doing the unglamorous work underneath. It's also my sandbox for agentic content tooling — where publishing pipelines get tried before I trust them anywhere else.",
      why: "Full-stack ownership of a live brand — design, web performance, CMS, and server ops — built and operated outside employer scaffolding.",
      stack: ["React", "Next.js", "Swift", "VPS"],
      metrics: [
        { k: "Surfaces", v: "site · CMS · VPS" },
        { k: "Craft", v: "lazy loading · fluid animation" },
      ],
      links: { demo: "https://artful-archives-website.vercel.app" },
      punchlist: { screenshot: "have", diagram: "need", gifVideo: "need", logoIcon: "need", publicUrl: "have", githubUrl: "need" },
      accent: "rose",
      art: ghibli("artful-archives"),
      cover: "assets/covers/bundles/artful.svg",
      foldsIn: [],
    },
    {
      id: "ant-zai", rank: 14, tier: "full", kind: "personal",
      codename: "ANT + ZAI", title: "Two public repos, zero redactions",
      readiness: "needs-media",
      one: "Public code: news agents + machine vision.",
      tagline: "A pair of public repos — autonomous agents that collect and transform AI news, and a multi-platform vision suite built on GLM-4.6V.",
      story: "These are the repos I point people at when they want to read actual code. Agentic News Transformer is a multi-agent ecosystem (LangChain + CrewAI) that collects, processes, and analyzes AI news. Zai Vision Suite is a multi-platform computer-vision toolkit on GLM-4.6V — real-time analysis, detection, scene understanding. No NDA, no sanitization — just the work.",
      why: "Public, inspectable applied-LLM and vision code — the open receipts behind the employer case studies.",
      stack: ["Python", "LangChain", "CrewAI", "GLM-4.6V"],
      metrics: [
        { k: "Repos", v: "2 — both public" },
        { k: "Vision model", v: "GLM-4.6V" },
      ],
      links: { github: "https://github.com/Ripnrip/Agentic-News-Transformer" },
      punchlist: { screenshot: "have", diagram: "need", gifVideo: "need", logoIcon: "need", publicUrl: "need", githubUrl: "have" },
      accent: "violet",
      art: ghibli("agentic-news-transformer"),
      cover: "assets/covers/bundles/ant-zai.svg",
      foldsIn: [
        { n: "Zai Vision Suite", href: "https://github.com/Ripnrip/zai-vision-suite" },
      ],
    },
    {
      id: "hackathons", rank: 15, tier: "full", kind: "proof-rail",
      codename: "Hackathon Reel", title: "The proof rail: 28+ hackathons, 2 firsts",
      readiness: "ship-ready",
      why: "A durable, documented pattern of fast prototyping, winning under constraints, and giving back as judge and mentor.",
      links: { github: "https://github.com/Ripnrip/ARon" },
      punchlist: { screenshot: "have", diagram: "n/a", gifVideo: "have", logoIcon: "need", publicUrl: "have", githubUrl: "have" },
      accent: "violet",
      cover: "assets/covers/bundles/hackathons.svg",
      foldsIn: [{ n: "Gurduwara Langar Game", href: "https://github.com/Ripnrip/GurduwaraLangarGame" }],
    },
  ],

  // Playground — the fun tiles that didn't fold into a bundle.
  // (13 former side projects were absorbed into the bundles above.)
  sideProjects: [
    { title: "Audio Dialogues", cat: "AI/ML", img: ghibli("audio-dialogues"), one: "Talk with AI, out loud.", desc: "Interactive AI audio conversations with natural speech synthesis.", tech: ["React", "Audio API", "AI"], link: "https://audio-dialogues.vercel.app" },
    { title: "Cycles of Fate", cat: "Creative", img: ghibli("cycles-of-fate"), one: "Generative art about destiny.", desc: "Dynamic web experience exploring fate and cosmic cycles through generative visuals.", tech: ["React", "Generative Art"], link: "https://cycles-of-fate.vercel.app/" },
    { title: "Geometric Graph Design", cat: "Creative", img: ghibli("geometric-graph"), one: "Sacred geometry, generated live.", desc: "Generative geometric visualizations from mathematical algorithms — sacred geometry.", tech: ["React", "Canvas", "Math"], link: "https://v0-geometric-graph-design.vercel.app/" },
  ],
};
